import type { BranchType, OptionType } from '@/core/types';
import { STAGE_STATUS } from '@core/constants/stageConstants';

// Mock master data for dropdowns
export const MASTER_MOCK_DATA = {
  BRANCHES: [
    { branchId: '1', branchDesc: 'Main Branch' },
    { branchId: '2', branchDesc: 'Secondary Branch' },
  ] as BranchType[],
  PRODUCTS: [
    { id: '101', label: 'Home Loan' },
    { id: '102', label: 'Car Loan' },
  ] as OptionType[],
  LOAN_TYPE: [
    { id: '201', label: 'Fixed Rate' },
    { id: '202', label: 'Floating Rate' },
  ] as OptionType[],
  SOURCE_NAME: [
    { id: '301', label: 'Source 1' },
    { id: '302', label: 'Source 2' },
  ] as OptionType[],
  SOURCE_TYPE: [
    { id: '4001', label: 'Source 1' },
    { id: '4002', label: 'Source 2' },
  ] as OptionType[],
  VENDOR: [
    { id: '401', label: 'Vendor A' },
    { id: '402', label: 'Vendor B' },
  ] as OptionType[],
  BANK: [
    { id: '501', label: 'Bank A' },
    { id: '502', label: 'Bank B' },
  ] as OptionType[],
  TIME_PERIOD: [
    { id: '601', label: '6 Months' },
    { id: '602', label: '1 Year' },
  ] as OptionType[],
  LOAN_PURPOSE: [
    { id: '701', label: 'Education' },
    { id: '702', label: 'Business' },
  ] as OptionType[],
  LOAN_AMOUNTS: [
    { id: '801', label: '₹10,00,000' },
    { id: '802', label: '₹20,00,000' },
  ] as OptionType[],
  PROPERTY_TYPES: [
    { id: '901', label: 'Apartment' },
    { id: '902', label: 'Villa' },
  ] as OptionType[],
  LANGUAGES: [
    { id: '1001', label: 'English' },
    { id: '1002', label: 'Hindi' },
  ] as OptionType[],
  SUB_LOAN_TYPE: [
    { id: '2001', label: 'Top-up with additional Property' },
    { id: '2002', label: 'Top-up with additional applicant' },
  ] as OptionType[],
  PROPERTY_USAGE: [
    { id: '3001', label: 'Self-Occupied' },
    { id: '3002', label: 'Rented Commercial Property' },
    { id: '3003', label: 'Rented Residential Property' },
  ] as OptionType[],
};

export const mockLeadData = [
  {
    leadId: 12345678,
    sourceName: 'Connected',
    mobileNo: '9876543210',
    firstName: 'John',
    middleName: 'A.',
    lastName: 'Smith',
  },
  {
    leadId: 87654321,
    sourceName: 'Not Connected',
    mobileNo: '9876543211',
    firstName: 'Jane',
    middleName: 'B.',
    lastName: 'Doe',
  },
  {
    leadId: 23456789,
    sourceName: 'Connected',
    mobileNo: '9876543212',
    firstName: 'Alice',
    middleName: 'C.',
    lastName: 'Johnson',
  },
  {
    leadId: 34567890,
    sourceName: 'Not Connected',
    mobileNo: '9876543213',
    firstName: 'Bob',
    middleName: 'D.',
    lastName: 'Brown',
  },
  {
    leadId: 45678901,
    sourceName: 'Connected',
    mobileNo: '9876543214',
    firstName: 'Charlie',
    middleName: 'E.',
    lastName: 'Lee',
  },
  {
    leadId: 56789012,
    sourceName: 'Connected',
    mobileNo: '9876543215',
    firstName: 'David',
    middleName: 'A.',
    lastName: 'Kim',
  },
  {
    leadId: 67890123,
    sourceName: 'Not Connected',
    mobileNo: '9876543216',
    firstName: 'Eva',
    middleName: 'B.',
    lastName: 'Green',
  },
  {
    leadId: 78901234,
    sourceName: 'Connected',
    mobileNo: '9876543217',
    firstName: 'Frank',
    middleName: 'C.',
    lastName: 'Hall',
  },
  {
    leadId: 89012345,
    sourceName: 'Not Connected',
    mobileNo: '9876543218',
    firstName: 'Grace',
    middleName: 'D.',
    lastName: 'Park',
  },
  {
    leadId: 90123456,
    sourceName: 'Connected',
    mobileNo: '9876543219',
    firstName: 'Henry',
    middleName: 'E.',
    lastName: 'White',
  },
  {
    leadId: 11223344,
    sourceName: 'Connected',
    mobileNo: '9876543220',
    firstName: 'Ivy',
    middleName: 'A.',
    lastName: 'Black',
  },
  {
    leadId: 22334455,
    sourceName: 'Not Connected',
    mobileNo: '9876543221',
    firstName: 'Jack',
    middleName: 'B.',
    lastName: 'Miller',
  },
  {
    leadId: 33445566,
    sourceName: 'Connected',
    mobileNo: '9876543222',
    firstName: 'Karen',
    middleName: 'C.',
    lastName: 'Davis',
  },
  {
    leadId: 44556677,
    sourceName: 'Not Connected',
    mobileNo: '9876543223',
    firstName: 'Leo',
    middleName: 'D.',
    lastName: 'Taylor',
  },
  {
    leadId: 55667788,
    sourceName: 'Connected',
    mobileNo: '9876543224',
    firstName: 'Mia',
    middleName: 'E.',
    lastName: 'Anderson',
  },
];

// Mock data for stage items
export const mockStageData = {
  stages: [
    {
      id: 'product-details',
      title: 'Product Details',
      description: 'Capture product details',
      status: STAGE_STATUS.COMPLETED,
      isPreLogin: true,
      hasUpdateAction: false,
      hasSummaryAction: true,
      hasContinueAction: false,
      subItems: [],
    },
    {
      id: 'stage-1',
      stageNumber: 1,
      title: 'Customer Details',
      description: 'Capture KYC details',
      status: STAGE_STATUS.COMPLETED,
      isPreLogin: false,
      hasUpdateAction: true,
      hasSummaryAction: true,
      hasContinueAction: false,
      subItems: [
        { id: 'pan', label: 'PAN', completed: true },
        { id: 'id-proof', label: 'ID Proof', completed: false },
        { id: 'selfie', label: 'Selfie', completed: false },
        { id: 'address-proof', label: 'Address Proof', completed: false },
        { id: 'personal-employment', label: 'Personal & Employment Details', completed: false },
      ],
    },
    {
      id: 'stage-2',
      stageNumber: 2,
      title: 'Property & Reference Details',
      description: 'Capture Property & Reference details',
      status: STAGE_STATUS.IN_PROGRESS,
      isPreLogin: false,
      hasUpdateAction: false,
      hasSummaryAction: false,
      hasContinueAction: true,
      subItems: [
        { id: 'property-details', label: 'Property Details', completed: false },
        { id: 'reference-details', label: 'Reference Details', completed: false },
      ],
    },
    {
      id: 'stage-3',
      stageNumber: 3,
      title: 'Bank Account Details',
      description: 'Capture Source Fee & Bank Account details',
      status: STAGE_STATUS.PENDING,
      isPreLogin: false,
      hasUpdateAction: false,
      hasSummaryAction: false,
      hasContinueAction: true,
      subItems: [],
    },
    {
      id: 'stage-4',
      stageNumber: 4,
      title: 'Bureau, Dedupe & FI Details',
      description: 'Cheque the CIBIL, Dedupe & FI',
      status: STAGE_STATUS.PENDING,
      isPreLogin: false,
      hasUpdateAction: false,
      hasSummaryAction: false,
      hasContinueAction: true,
      subItems: [],
    },
    {
      id: 'stage-5',
      stageNumber: 5,
      title: 'Document Collection',
      description: 'Collect the documents from the user',
      status: STAGE_STATUS.PENDING,
      isPreLogin: false,
      hasUpdateAction: false,
      hasSummaryAction: false,
      hasContinueAction: true,
      subItems: [],
    },
  ],
};
